/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictionsIndexRouteImport } from './routes/predictions.index'
import { Route as PredictionsSlugRouteImport } from './routes/predictions.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPredictionsRouteImport } from './routes/_authenticated/admin.predictions'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminFootballRouteImport } from './routes/_authenticated/admin.football'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin.comments'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'
import { Route as AuthenticatedAdminPredictionsIndexRouteImport } from './routes/_authenticated/admin.predictions.index'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated/admin.articles.index'
import { Route as ApiPublicHooksFootballSyncRouteImport } from './routes/api/public/hooks/football-sync'
import { Route as AuthenticatedAdminPredictionsNewRouteImport } from './routes/_authenticated/admin.predictions.new'
import { Route as AuthenticatedAdminPredictionsIdRouteImport } from './routes/_authenticated/admin.predictions.$id'
import { Route as AuthenticatedAdminArticlesNewRouteImport } from './routes/_authenticated/admin.articles.new'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin.articles.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsIndexRoute = PredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsSlugRoute = PredictionsSlugRouteImport.update({
  id: '/predictions/$slug',
  path: '/predictions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPredictionsRoute =
  AuthenticatedAdminPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFootballRoute =
  AuthenticatedAdminFootballRouteImport.update({
    id: '/football',
    path: '/football',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPredictionsIndexRoute =
  AuthenticatedAdminPredictionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPredictionsRoute,
  } as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const ApiPublicHooksFootballSyncRoute =
  ApiPublicHooksFootballSyncRouteImport.update({
    id: '/api/public/hooks/football-sync',
    path: '/api/public/hooks/football-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPredictionsNewRoute =
  AuthenticatedAdminPredictionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPredictionsRoute,
  } as any)
const AuthenticatedAdminPredictionsIdRoute =
  AuthenticatedAdminPredictionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPredictionsRoute,
  } as any)
const AuthenticatedAdminArticlesNewRoute =
  AuthenticatedAdminArticlesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/predictions/': typeof PredictionsIndexRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRouteWithChildren
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/football': typeof AuthenticatedAdminFootballRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/predictions': typeof AuthenticatedAdminPredictionsRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
  '/admin/predictions/$id': typeof AuthenticatedAdminPredictionsIdRoute
  '/admin/predictions/new': typeof AuthenticatedAdminPredictionsNewRoute
  '/api/public/hooks/football-sync': typeof ApiPublicHooksFootballSyncRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/predictions/': typeof AuthenticatedAdminPredictionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/predictions': typeof PredictionsIndexRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/football': typeof AuthenticatedAdminFootballRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
  '/admin/predictions/$id': typeof AuthenticatedAdminPredictionsIdRoute
  '/admin/predictions/new': typeof AuthenticatedAdminPredictionsNewRoute
  '/api/public/hooks/football-sync': typeof ApiPublicHooksFootballSyncRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/predictions': typeof AuthenticatedAdminPredictionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/predictions/': typeof PredictionsIndexRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRouteWithChildren
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/football': typeof AuthenticatedAdminFootballRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/predictions': typeof AuthenticatedAdminPredictionsRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/_authenticated/admin/articles/new': typeof AuthenticatedAdminArticlesNewRoute
  '/_authenticated/admin/predictions/$id': typeof AuthenticatedAdminPredictionsIdRoute
  '/_authenticated/admin/predictions/new': typeof AuthenticatedAdminPredictionsNewRoute
  '/api/public/hooks/football-sync': typeof ApiPublicHooksFootballSyncRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/_authenticated/admin/predictions/': typeof AuthenticatedAdminPredictionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/article/$slug'
    | '/category/$slug'
    | '/predictions/$slug'
    | '/predictions/'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/football'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/predictions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/predictions/$id'
    | '/admin/predictions/new'
    | '/api/public/hooks/football-sync'
    | '/admin/articles/'
    | '/admin/predictions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/article/$slug'
    | '/category/$slug'
    | '/predictions/$slug'
    | '/predictions'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/football'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/predictions/$id'
    | '/admin/predictions/new'
    | '/api/public/hooks/football-sync'
    | '/admin/articles'
    | '/admin/predictions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/article/$slug'
    | '/category/$slug'
    | '/predictions/$slug'
    | '/predictions/'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/football'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/predictions'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/articles/$id'
    | '/_authenticated/admin/articles/new'
    | '/_authenticated/admin/predictions/$id'
    | '/_authenticated/admin/predictions/new'
    | '/api/public/hooks/football-sync'
    | '/_authenticated/admin/articles/'
    | '/_authenticated/admin/predictions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PredictionsSlugRoute: typeof PredictionsSlugRoute
  PredictionsIndexRoute: typeof PredictionsIndexRoute
  ApiPublicHooksFootballSyncRoute: typeof ApiPublicHooksFootballSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/': {
      id: '/predictions/'
      path: '/predictions'
      fullPath: '/predictions/'
      preLoaderRoute: typeof PredictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/$slug': {
      id: '/predictions/$slug'
      path: '/predictions/$slug'
      fullPath: '/predictions/$slug'
      preLoaderRoute: typeof PredictionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/predictions': {
      id: '/_authenticated/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AuthenticatedAdminPredictionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/football': {
      id: '/_authenticated/admin/football'
      path: '/football'
      fullPath: '/admin/football'
      preLoaderRoute: typeof AuthenticatedAdminFootballRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/predictions/': {
      id: '/_authenticated/admin/predictions/'
      path: '/'
      fullPath: '/admin/predictions/'
      preLoaderRoute: typeof AuthenticatedAdminPredictionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPredictionsRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/api/public/hooks/football-sync': {
      id: '/api/public/hooks/football-sync'
      path: '/api/public/hooks/football-sync'
      fullPath: '/api/public/hooks/football-sync'
      preLoaderRoute: typeof ApiPublicHooksFootballSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/predictions/new': {
      id: '/_authenticated/admin/predictions/new'
      path: '/new'
      fullPath: '/admin/predictions/new'
      preLoaderRoute: typeof AuthenticatedAdminPredictionsNewRouteImport
      parentRoute: typeof AuthenticatedAdminPredictionsRoute
    }
    '/_authenticated/admin/predictions/$id': {
      id: '/_authenticated/admin/predictions/$id'
      path: '/$id'
      fullPath: '/admin/predictions/$id'
      preLoaderRoute: typeof AuthenticatedAdminPredictionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminPredictionsRoute
    }
    '/_authenticated/admin/articles/new': {
      id: '/_authenticated/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AuthenticatedAdminArticlesNewRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
    '/_authenticated/admin/articles/$id': {
      id: '/_authenticated/admin/articles/$id'
      path: '/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminArticlesRoute
    }
  }
}

interface AuthenticatedAdminArticlesRouteChildren {
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesNewRoute: typeof AuthenticatedAdminArticlesNewRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
}

const AuthenticatedAdminArticlesRouteChildren: AuthenticatedAdminArticlesRouteChildren =
  {
    AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
    AuthenticatedAdminArticlesNewRoute: AuthenticatedAdminArticlesNewRoute,
    AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
  }

const AuthenticatedAdminArticlesRouteWithChildren =
  AuthenticatedAdminArticlesRoute._addFileChildren(
    AuthenticatedAdminArticlesRouteChildren,
  )

interface AuthenticatedAdminPredictionsRouteChildren {
  AuthenticatedAdminPredictionsIdRoute: typeof AuthenticatedAdminPredictionsIdRoute
  AuthenticatedAdminPredictionsNewRoute: typeof AuthenticatedAdminPredictionsNewRoute
  AuthenticatedAdminPredictionsIndexRoute: typeof AuthenticatedAdminPredictionsIndexRoute
}

const AuthenticatedAdminPredictionsRouteChildren: AuthenticatedAdminPredictionsRouteChildren =
  {
    AuthenticatedAdminPredictionsIdRoute: AuthenticatedAdminPredictionsIdRoute,
    AuthenticatedAdminPredictionsNewRoute:
      AuthenticatedAdminPredictionsNewRoute,
    AuthenticatedAdminPredictionsIndexRoute:
      AuthenticatedAdminPredictionsIndexRoute,
  }

const AuthenticatedAdminPredictionsRouteWithChildren =
  AuthenticatedAdminPredictionsRoute._addFileChildren(
    AuthenticatedAdminPredictionsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRouteWithChildren
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminFootballRoute: typeof AuthenticatedAdminFootballRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminPredictionsRoute: typeof AuthenticatedAdminPredictionsRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRouteWithChildren,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
  AuthenticatedAdminFootballRoute: AuthenticatedAdminFootballRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminPredictionsRoute:
    AuthenticatedAdminPredictionsRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  PredictionsSlugRoute: PredictionsSlugRoute,
  PredictionsIndexRoute: PredictionsIndexRoute,
  ApiPublicHooksFootballSyncRoute: ApiPublicHooksFootballSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
